name: Lint

on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    - uses: actions/checkout@v1
    - uses: stefanoeb/eslint-action@1.0.2
    steps:
     - name: Install Dependencies
      run: |
      npm install
